/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollegesRouteImport } from './routes/colleges'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CorporatesRouteImport } from './routes/corporates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesRoute = CollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporatesRoute = CorporatesRouteImport.update({
  id: '/corporates',
  path: '/corporates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colleges': typeof CollegesRoute
  '/contact': typeof ContactRoute
  '/corporates': typeof CorporatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colleges': typeof CollegesRoute
  '/contact': typeof ContactRoute
  '/corporates': typeof CorporatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colleges': typeof CollegesRoute
  '/contact': typeof ContactRoute
  '/corporates': typeof CorporatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/colleges' | '/contact' | '/corporates'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/colleges' | '/contact' | '/corporates'
  id: '__root__' | '/' | '/colleges' | '/contact' | '/corporates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollegesRoute: typeof CollegesRoute
  ContactRoute: typeof ContactRoute
  CorporatesRoute: typeof CorporatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges': {
      id: '/colleges'
      path: '/colleges'
      fullPath: '/colleges'
      preLoaderRoute: typeof CollegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporates': {
      id: '/corporates'
      path: '/corporates'
      fullPath: '/corporates'
      preLoaderRoute: typeof CorporatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollegesRoute: CollegesRoute,
  ContactRoute: ContactRoute,
  CorporatesRoute: CorporatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
